// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pacagroup.Trade.Persistence.Contexts;

#nullable disable

namespace Pacagroup.Trade.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260305060111_AlterOrderScheme")]
    partial class AlterOrderScheme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pacagroup.Trade.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .HasPrecision(9)
                        .HasColumnType("int");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValue("USD");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("Price")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<int>("Quanty")
                        .HasPrecision(9)
                        .HasColumnType("int");

                    b.Property<int>("Side")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Text")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("TransactTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateBy = "System",
                            Created = new DateTime(2026, 3, 5, 6, 1, 10, 402, DateTimeKind.Utc).AddTicks(1516),
                            Currency = "USD",
                            Price = 522.99m,
                            Quanty = 1000,
                            Side = 0,
                            Symbol = "META",
                            Text = "",
                            TransactTime = new DateTime(2026, 3, 5, 6, 1, 10, 402, DateTimeKind.Utc).AddTicks(1506),
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            CreateBy = "System",
                            Created = new DateTime(2026, 3, 5, 6, 1, 10, 402, DateTimeKind.Utc).AddTicks(1522),
                            Currency = "USD",
                            Price = 424.30m,
                            Quanty = 300,
                            Side = 0,
                            Symbol = "MSFT",
                            Text = "",
                            TransactTime = new DateTime(2026, 3, 5, 6, 1, 10, 402, DateTimeKind.Utc).AddTicks(1520),
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            CreateBy = "System",
                            Created = new DateTime(2026, 3, 5, 6, 1, 10, 402, DateTimeKind.Utc).AddTicks(1526),
                            Currency = "USD",
                            Price = 0m,
                            Quanty = 400,
                            Side = 1,
                            Symbol = "AMZN",
                            Text = "",
                            TransactTime = new DateTime(2026, 3, 5, 6, 1, 10, 402, DateTimeKind.Utc).AddTicks(1524),
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            CreateBy = "System",
                            Created = new DateTime(2026, 3, 5, 6, 1, 10, 402, DateTimeKind.Utc).AddTicks(1529),
                            Currency = "USD",
                            Price = 0m,
                            Quanty = 800,
                            Side = 0,
                            Symbol = "GOOGL",
                            Text = "",
                            TransactTime = new DateTime(2026, 3, 5, 6, 1, 10, 402, DateTimeKind.Utc).AddTicks(1528),
                            Type = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
